lib/response.js

While reviewing the `handle-errors` PR some repetitive logic stood out to me. This PR is my solution to reducing it. It may not be worth merging, but I figured it's a least worth consideration.

Reduce repetitive logic a bit

---

index.js
lib/response.js
package.json
test/async-await.js
test/test.js

As titled.
This is a breaking change in the api.
Related: https://github.com/fastify/light-my-request/issues/10 and https://github.com/fastify/fastify/pull/617#issuecomment-355526614
~~@mcollina [Those](https://github.com/fastify/light-my-request/blob/handle-errors/test/test.js#L608-L650) test are failing, any idea why?~~
cc @fastify/fastify

Added error handling

---

index.js
package.json
test/async-await.js
test/test.js

From https://github.com/fastify/fastify/pull/883#issuecomment-382182010

Only http.METHODS

---

README.md
index.js
lib/request.js
test/test.js

See [Help #46](https://github.com/fastify/help/issues/46)

Add `query` option

---

README.md

In case we want to provide an example for #35

Add example snippet for file upload

---

.travis.yml

Add testing of Node v12 to the test rig.

Add Node 12 to Travis

---

lib/response.js
test/test.js

Add json() handler for Response

---

index.d.ts

Update TypeScript typings (#57)

---

package.json

chore(package): update @types/node to version 12.11.6

---

README.md
index.d.ts
index.js
test/async-await.js
test/index.test-d.ts
test/test.js

The original issue is https://github.com/fastify/light-my-request/issues/50.
And I'm glad to update the document and typings if this feature is accepted.

Chainable api support

---

index.js

Remove throw utility

---

index.js
test/test.js

fix regression introduced in v3.6.0 with string urls

---

.dependabot/config.yml
README.md
package.json

move to dependabot

---

index.d.ts
test/index.test-d.ts

fix(): type in protocol

---

test/test.js

Removed warning in the test

---

index.js

Make the TypeScript example work:
`import { inject, DistpatchFunc } from 'light-my-request'`
*missing script: benchmark*

module.exports.inject = inject

---

.github/workflows/ci.yml
README.md
package.json

 chore: ci updates and style change

---

lib/parseURL.js
lib/request.js
package.json
test/benchmark.js

Before changes
```
Request x 143,422 ops/sec ±1.22% (85 runs sampled)
Request With Cookies x 121,947 ops/sec ±0.85% (89 runs sampled)
Request With Cookies n payload x 115,137 ops/sec ±1.23% (89 runs sampled)
ParseUrl x 292,202 ops/sec ±0.92% (94 runs sampled)
ParseUrl and query x 210,294 ops/sec ±1.12% (93 runs sampled)
```
After changes:
```
Request x 190,980 ops/sec ±0.82% (90 runs sampled)
Request With Cookies x 150,045 ops/sec ±0.62% (95 runs sampled)
Request With Cookies n payload x 141,071 ops/sec ±1.04% (94 runs sampled)
ParseUrl x 288,184 ops/sec ±0.56% (94 runs sampled)
ParseUrl and query x 211,901 ops/sec ±1.28% (95 runs sampled)
```
I guess the changes in ParseUrl is not significant to make a drastic change in perf, but it fits the coding style.
and the [Code of …

Feat: Speed improvement

---

package.json

Used here: https://github.com/fastify/light-my-request/blob/014c1c8016f8605b5ca4c7906f527d5ab0b17267/test/test.js#L12

chore: add missing semver dev dependency

---

lib/response.js
package.json
test/test.js

Fixes https://github.com/fastify/fastify-express/issues/47

fix: copy headers when using express

---

index.d.ts
test/index.test-d.ts

Fix Response type

---

lib/request.js
package.json

Updating process-warning

---

lib/request.js
test/request.test.js

Fixes #217. In general though, a more robust approach might be to subclass Node's request object instead of trying to mimic its behavior.

fix: request has aborted flag set to false

---

lib/request.js

use hasOwnProperty from Object.prototype

---

test/index.test-d.ts

As pointed out in #221, type tests are currently failing

chore: fix type test

---

lib/response.js

See https://github.com/fastify/fastify-express/issues/47#issuecomment-1242671020
Fixes https://github.com/fastify/fastify-express/issues/47

fix: add back `headers` copying code

---

types/index.d.ts
types/index.test-d.ts

type only change, benchmark is not necessary

add response cookies type

---

types/index.d.ts
types/index.test-d.ts

Fix type in CallbackFunc
add possible undefined to arguments

fix type CallbackFunc
