README.md, index.js, package.json, test/test.js
Bind this to http server instance
The right behaviour calling the handler to the `request` event. All events are fired binding `this` to the event emitter.
=> Bind this to server instance

lib/request.js, lib/response.js, package.json
As long as Fastify intends to support Node 4 then this needs to use the `safe-buffer` module.
=> Use safe-buffer for Node 4 compatibility (fix #8)

README.md
The code allows calling `inject(dispatch, '/url')` as a shorthand for `inject(dispatch, {url: '/url'})`. This change documents that shorthand.
=> Document url string shorthand

lib/request.js, package.json, test/test.js
As titled, if the payload is a stream, `light-my-request` should force its resume.
Fix https://github.com/fastify/fastify/pull/1026
=> Force stream resume

.travis.yml, lib/request.js, lib/response.js, package.json, test/test.js
It also adds support for faux streams and relies on duck typing.
Removes support for Node 4, 5, 7 and 9.
Removes support for safe-buffer as it's not needed anymore.
This will be a semver-major change for light-my-request (dropped old nodes support), but we can drop it in fastify as a minor (not breaking for them).
=> Adds support for readable-stream@3.

README.md, lib/request.js, lib/response.js, test/test.js
In the rest for the Fastify API, we use the term body to identify the body of a request.
Here is called payload. I find that extremely confusing.
=> Added body -> payload aliases tog match the rest of Fastify APIs

README.md, index.d.ts, package.json, test/index.test-d.ts, tsconfig.json
Spent some time trying to complete this tonight. Please review as accurately as possible. All of my types are from reading the code. I based some off of the JSON Schema object but also included anything written in the documentation too. There were a couple `any` types I'd like to see if we can make more specific, as well as some general questions I have: 
- Is the `port` property on the `InjectOptions.url` type of `string | number`?
- What is `query`? Could this be typed as `string`?
- What types can `payload` be? I've implemented it as a generic for now but I think we can scope this to an union type list: `string | object | Buffer | NodeJS.ReadableStream` (this is actually copied from the current `fastify.d.ts` types `HTTPInjectOptions` so I believe it should be safe to implement here as …
=> Add TypeScript typings

README.md, index.d.ts, index.js, lib/request.js, test/test.js
Since in the Fastify route declaration we support both `url` and `path`, we should do the same here.
=>  Use path as alias of url

lib/response.js
Fixes _headers deprecation warning in Node v12. See issue #44
=> Fix dep0066

README.md, index.d.ts, test/index.test-d.ts
=> Update doc and typings for res.json()

README.md, index.js, test/test.js
This restores a behavior that was lost when adding the Chain capability.
=> restore autostart when using fire-and-forget promises.

lib/response.js, test/test.js
=> Override Response.setTimeout to make response timeout handler work

README.md, index.d.ts, index.js, lib/request.js, lib/response.js, package.json, test/index.test-d.ts, test/test.js
=> Easy cookie

index.js, lib/request.js, test/test.js
Headers value must be a string, but adding key to a javascript object sometimes by mistake you could add a number, an array, an object or something different from a string.
In this case, the test may incorrectly pass.
=> Validate headers value

index.d.ts, test/index.test-d.ts
=> Add cookies property to the InjectOptions interface type definition

index.d.ts, test/index.test-d.ts
this PR fixes wrong typescript definitions for the `query` object in `HttpInjectOptions`.
=> fix incorrect typescript defs for query

index.d.ts, test/index.test-d.ts
The implementation allows to provide multiple query param values for the same key like: `query: { fields: ["a", "b"] }`. This PR adds the corresponding type definitions to stay in sync with the implementation.
=> Add missing query param multi-value type definition

index.d.ts, test/index.test-d.ts
fixes #82
inspired by #83
type `any` was chosen as per instructions from @mcollina to replicate what JSON.parse is returning.
=> Fix type for Response.json()

index.d.ts, test/index.test-d.ts
Currently `end()` is useless because even when it's used TypeScript complains about value potentially being `Chain` and does not compile properly without explicit casts or ignores.
However, it doesn't look like `Chain` is actually ever returned from that code:
```
Chain.prototype.end = function (callback) {
if (this._hasInvoked === true || this._promise) {
throw new Error(errorMessage)
}
this._hasInvoked = true
if (typeof callback === 'function') {
doInject(this.dispatch, this.option, callback)
} else {
this._promise = doInject(this.dispatch, this.option)
return this._promise
}
}
```
=> Fix type returned by `end()`

index.d.ts, test/index.test-d.ts
It's added here: https://github.com/fastify/light-my-request/blob/master/lib/response.js#L40
- Note: couldn't find anything about commit message requirements
=> Add missing type for Response.raw.req

lib/response.js
I wanted to cover Line 130 in `repsonse.js`:
```
response.js         |    98.65 |    85.71 |    95.24 |    98.55 |               130 |
```
Already had a test case to cover this: 
```
test('Response.json() should throw an error if content-type is not application/json'
```
Which was passing, but throwing a different error to what we expect and therefore never entering Line 130. 
```
type: TypeError
message: Cannot read property 'headers' of undefined
source: >2
res.json = function parseJsonPayload () {
if (this.headers['content-type'].indexOf('application/json') < 0) {
-------------^
throw new Error('The content-type of the response is not application/json')
}
```
Tests pass and coverage is increased.
=> fix: change this to res in response.js

index.d.ts, test/index.test-d.ts
It's better to use an optional generic for response json parser method:
Sample usage:
```ts
interface Response {
code: string
}
async function getCode(): string {
const result = await inject(dispatch)
return result.json<Response>().code
}
```
=> [feat types] using generic type for request json parser

index.d.ts, lib/request.js, package.json, test/test.js
Fixes #87.  This adds the `.socket` property to `request`, mirroring the `.connection` property
=> fix: add missing request.socket (#87)

lib/response.js, package.json, test/test.js
Resolve #90 
For ```request.js``` L121
I do not see a reason the request will be end early without custom alter the ```_lightMyRequest``` object.
So, I decided to alter it in ```dispatch``` in order to reach the the line and pretend it is a invalid alter by user.
For ```response.ts``` L62
If this plugin do not support node 7.7.0 or early, this is never happen for the false condition.
[NodeJS Docs](https://nodejs.org/api/http.html#http_response_getheaders) for ```getHeaders```
=> test: :white_check_mark: improve test line coverage

lib/request.js, test/test.js
Before this change, if a Fastify user attached an `onTimeout` hook to their server, an error would be thrown in test mode when injecting requests with light-my-request
```
TypeError: request.raw.socket.on is not a function
at Object.routeHandler [as handler] (../../node_modules/fastify/lib/route.js:350:28)
at Router.lookup (../../node_modules/find-my-way/index.js:356:14)
at ../../node_modules/light-my-request/index.js:101:38
at Request.prepare (../../node_modules/light-my-request/lib/request.js:110:12)
at ../../node_modules/light-my-request/index.js:101:11
at doInject (../../node_modules/light-my-request/index.js:97:12)
at Chain.<computed> [as then] (../../node_modules/light-my-request/index.js:187:23)
at runMicrotasks (<anonymous>)
```
This fixes the socket object to have an `on` …
=> Expose a mock socket that is an EventEmitter like a real one would be

.gitignore, index.js, lib/request.js, lib/response.js, package.json, test/response.test.js, test/test.js
- Implemented the missing `Response.prototype.destroy` 
- Fixed test
The test was there for destroy, but it never failed because it didn't have `t.plan` so the test didn't make sure the `inject` response callback was ever called.
=> fix: fix response.destroy

index.d.ts, test/async-await.js, test/index.test-d.ts, test/test.js
ref: #109 
On my local the following assertion is not valid:
```js
Number(process.versions.node[0]) >= 8 // it returns 1 for node v12.18.3
```
So, changed to `semver` check to prevent bugs
=> Fix typescript chain response

lib/parseURL.js, package.json, test/test.js
=> fixed parseURL and all tests passed for bug: Value of request.url when using .inject differs from a real server #3257

index.d.ts, lib/request.js, test/test.js
I've noticed that Request does not contain rawHeaders property when I was unable to test proxy example from undici repository, see here: https://github.com/nodejs/undici/blob/main/examples/proxy/proxy.js#L9
=> added rawHeaders to Request

lib/response.js, test/test.js
Unfortunately using this together with `stream.finished()` did not work as expected in Node v16.
=> Correctly support finished in Node v16

lib/request.js, lib/response.js, test/test.js
Close #212 
Pass the real req to ServerResponse, then it can be used with pipeline().
* https://github.com/nodejs/node/blob/96601cc759aa6f54f9cf9db466a004cb57ede651/lib/_http_server.js
* https://github.com/nodejs/node/blob/96601cc759aa6f54f9cf9db466a004cb57ede651/lib/internal/streams/end-of-stream.js
=> fix: pass req to ServerResponse to support pipeline() on node 16

lib/request.js, test/test.js
@budarin
I open this PR to see if the unit tests run.
=> make user-agent and content-type overwritable with undefined

index.js, lib/response.js, test/test.js
Took test from #155 
Also reverted changes in `response.js` made in #154
~`tsd` tests seems to fail on master too~ fixed in #222 
=> fix: properly handle Express.js send payload

README.md, lib/response.js, test/test.js
=> fix: Response.json() should not check the content-type

lib/request.js, test/index.test.js
Adding fake origin header as per #235
=> #235 Add fake origin header

types/index.d.ts, types/index.test-d.ts
`body` is an alias for `payload`, but was missing from the types.
=> fix: add missing type for request body

lib/request.js, test/index.test.js
This change prevents an unwanted `undefined` error when using this in combination with fastify-http-proxy: https://github.com/fastify/fastify-http-proxy/pull/305
=> Calling req.destroy() after reading the whole payload should not error

lib/response.js, test/index.test.js
=> dont serialize null as header values

README.md, benchmark/benchmark.js, build/build-validation.js, index.js, lib/parse-url.js, lib/request.js, lib/response.js, test/index.test.js
See https://github.com/fastify/fastify-static/pull/407
=> perf: use `node:` prefix to bypass require.cache call for builtins

benchmark/benchmark.js, package.json
Add async benchmarks
use process.hrtime()
=> Improve benchmarks
